# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: go-backend
package: your-package

# Directory
dir:
  # client
  controller: internal/delivery/http/controller