# Lokio Configuration File
# Author: Lokio
# Github: https://github.com/any-source/lokio
# Documentation: https://lokio.dev

name: next-monolith
package: your-package

# Directory
dir:
  # client
  hook: src/hooks
  shared: src/shared
  call: src/call
  component: src/interfaces/components
  screen: src/interfaces/screens
  layout: src/interfaces/layouts

  # server
  controller: src/server/controllers
  middleware: src/server/middlewares
  service: src/server/services
  schema: src/server/schemas
